TheFolio/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('profil.urls')),
    path('pwoje/',include('projet.urls'))
]

#news

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profil/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.acceuil ,name='aceuil'),
    path('onProfile/<int:id>',views.itilizate, name='onprofile'),
    path('create/',views.newItilizate,name='create'),
    path('dekonekte/',views.dekonekte,name='dekonekte'),
    path('newprofil/',views.newprofil,name='newprofil'),
    path('konekuser/',views.konekUser,name='konekuser'),
    
    

]

projet/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.acceuil ,name='acceuil'),
    path('yonproje/<str:slug>',views.one,name='youn'),
    path('kreyee',views.newProje, name='kreyee'),
    path('delete/<int:id>',views.suprime,name='delete')
]

profil/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    nom=models.CharField(max_length=200 ,null=True,)
    siyati=models.CharField(max_length=200, null=True)
    email=models.EmailField(max_length=100, null=True)
    telefon=models.CharField(max_length=40, null=True, blank=True)
    foto=models.ImageField(upload_to='my_picture/', blank=True, null=True)


    def __str__(self):
        return str(self.nom)
    


class Kategori(models.Model):
    kate=(
        ('design','design'),
         ('food','food'),
         ('education','education'),
         ('energy','energy'),
         ('technology','technology'),
         ('programming','programming'),
         ('health','health'),
         ('finance','finance'),
         ('money','money') 
    )
    nom=models.CharField(max_length=150, choices=kate)
    def __str__(self):
        return self.nom

projet/models.py
from django.db import models
from profil.models import Kategori ,Profile
from django.utils.text import slugify
import random
from django.contrib.auth.models import User
# Create your models here

class Projet(models.Model):
    categori=models.ManyToManyField(Kategori ,blank=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    slug=models.SlugField(max_length=200,unique=True)
    titre=models.CharField(max_length=200, blank=True, null=True)
    description=models.TextField(max_length=5000, blank=True)
    date=models.DateTimeField(auto_now_add=True)
    foto=models.ImageField(upload_to='image/',blank=True)
    is_delete=models.BooleanField(default=False)

    def save(self, *args,**kwargs) :
        if self.pk is None:
            slug_m= slugify(self.titre)
            while Projet.objects.filter(slug=slug_m):
                slug_m+=str(random.randrange(1,2500))
            self.slug=slug_m
        super(Projet,self).save(args,kwargs)

    def __str__(self):
        return self.titre

profil/forms.py
from .models import Profile
from django import forms

class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=('nom','siyati','email','telefon','foto')

projet/forms.py
from dataclasses import fields
from distutils.command.upload import upload
from logging import PlaceHolder
from random import choice
from django import forms
from .models import Projet


class projetForm(forms.ModelForm):
        class Meta:
            model=Projet
            fields=('categori','titre','description','foto')
            widgets={
                'categori':forms.SelectMultiple(attrs={'class':'form-control'}),
                'titre':forms.TextInput(attrs={'class':'form-control'}),
                'description':forms.Textarea(attrs={'class':'form-control'}),
                'foto':forms.FileInput(attrs={'class':'form-control'})
            }

profil/views.py
from django.contrib.auth import authenticate, login,logout
from django.shortcuts import render,redirect 
from projet.models import Projet
from profil.models import Profile,Kategori
from django.contrib.auth.models import User
from .forms import ProfileForm
from django.db.models import Prefetch

from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def acceuil(request):
    Lis_itilizate=User.objects.select_related('profile').prefetch_related(Prefetch ('projet_set',queryset=Projet.objects.all().order_by('date')))
    #Lis_itilizate=User.objects.select_related('profile').all()
    context={
        'Lis_itilizate':Lis_itilizate
    }
    return render(request,'user/acceuil.html',context)




def itilizate(request,id):
    user=User.objects.select_related('profile').prefetch_related(Prefetch('projet_set',queryset=Projet.objects.all())).filter(id=id)
        
    context={
        'user':user
        
    }
    return render(request,'user/itilizate.html',context)
  
def newItilizate(request):
    if request.method == 'POST':
        nom=request.POST.get('nom')
        modpas=request.POST.get('modpas')
        confirm=request.POST.get('confirm')
        if modpas != confirm:
            pass
        else:
            user=User.objects.create_user(username=nom,password=modpas)
            login(request,user)
            return redirect(acceuil)


    return render(request,'user/kont.html')


def konekUser(request):
    if request.method== 'POST':
        nom=request.POST['nom']
        modpas=request.POST['modpas']
        user=authenticate(username=nom,password=modpas)
        if user is not None:
            login (request,user)
            return redirect(acceuil)
    
    return render(request,'user/konekte.html')



def newprofil(request):
    if request.method=='POST':
        form=ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile=form.save(commit=False)
            profile.user=request.user
            profile.save()
        return redirect(acceuil)
    else:
        form= ProfileForm()

    context={
        'form':form
    }
    return render(request,'user/kreyemoun.html',context)
 


def dekonekte(request):
    logout(request)
    return redirect(acceuil)

projet/views.py
from django.shortcuts import render,redirect
from .models import Projet
from profil.views import konekUser ,itilizate
from profil.models import Kategori , Profile
from .forms import projetForm
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
# Create your views here.
def acceuil(request):
    return render(request,'pwoje/acceuil.html')

def one(request,slug):
    un=Projet.objects.filter(is_delete=False).get(slug=slug)
    context={
        'un':un,

        }
    return render(request,'pwoje/unprojet.html',context)

@login_required(login_url='konekuser')
def newProje(request):

    if request.method=='POST':
            form=projetForm(data=request.POST,files=request.FILES)
            if form.is_valid():
                proje=form.save(commit=False)
                proje.user = request.user
                proje.save()
                return redirect('/')
            else:
                pass
    else:
        form=projetForm()
    context={
        'form':form
    }
    return render(request,'pwoje/kreye.html',context)

@login_required(login_url='konekuser')
def suprime(request,id ):
    referer_url=request.META.get('HTTP_REFERER','/')
    efase=Projet.objects.get(id=id)
    efase.delete()
   
    return redirect(referer_url)
        
        
    

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  
<head>
  <title>PortFolio</title>
  <meta charset="utf-8" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
</head>
<body>
  
  <!-- Header -->
    <header id="header">
      <div class="inner">
        <a href="/" class="logo"><strong>PORTFOLIO</strong></a>
        <nav id="nav">
          <a class="nav-link active" aria-current="page" href="{% url 'aceuil' %}">Acceuil</a>
             
          {% if request.user.is_authenticated %}

           <a class="nav-link" href="{% url 'kreyee' %}">New project</a>
           <a class="nav-link" href="{% url 'dekonekte' %}">Log out</a>
           <a class="nav-link" href="{% url 'newprofil' %}">Create Profil</a>
           {%else%}
           <a class="nav-link" href="{% url 'create' %}">New account</a>
           <a class="nav-link" href="{% url 'konekuser' %}">Sign in</a>
           
           {% endif %}
           <a href="#navPanel" class="navPanelToggle"><span class="fa fa-bars"></span></a>
				</div>
      </div>
    </header>
    
  <!-- Banner -->
    <section id="banner">
      <div class="inner">
        <header>
          <h1>Welcome on Portfolio</h1>
        </header>
        
        <div class="flex ">

          <div>
            <span class=" fa fa-user-circle"></span>
            <h3>Make a project</h3>
            <p>on your Profile</p>
          </div>

          <div>
            <span class="icon fa-camera"></span>
            <h3>Enjoy with us</h3>
            <p>when u are connect you can create your project everywhere</p>
          </div>

          <div>
            <span class=" fa fa-user-circle"></span>
            <h3>Make a profile</h3>
            <p>with our portfolio</p>
          </div>

        </div>

        <footer>
          <a class="button" href="{% url 'konekuser' %}">Sign in</a>
         <!-- <a href="#" class="button">Get Started</a>-->
        </footer>
      </div>
    </section>
    

<!-- Scripts -->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/skel.min.js' %}"></script>
<script src="{% static 'assets/js/util.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
   

{% block content %}

{% endblock content %}
    



 
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>





<style>
  footer .main-footer{ 
                padding: 20px 20px; 
                background: #252525;  
                overflow-y: hidden;}


/* Copy Right Footer */
.footer-copyright {
     background: #222; 
     padding: 10px 0; 
     margin-top: 250px; 
     overflow-y: hidden;}

.footer-copyright p { color: #969696;
                    margin: 2px 0 0;}



</style>
<footer id="footer" class="footer-1">
         
  <div class="footer-copyright">
  <div class="container">
  <div class="row">
  <div class="col-md-12 text-center">
  <p>Copyright Design by JEUDY © 2022. All rights reserved.</p>
  </div>
  </div>
  </div>
  </div>
  </footer>

    
</html>

</html>

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=h1, initial-scale=1.0">
    <title>PortFolio</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/style.css' %} " type="text/css">

</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            
              <a class="nav-link active" aria-current="page" href="{% url 'aceuil' %}">Acceuil</a>
             
             {% if request.user.is_authenticated %}

              <a class="nav-link" href="{% url 'kreyee' %}">New project</a>
              <a class="nav-link" href="{% url 'dekonekte' %}">Log out</a>
              <a class="nav-link" href="{% url 'newprofil' %}">Create Profil</a>
              {%else%}
              <a class="nav-link" href="{% url 'create' %}">New account</a>
              <a class="nav-link" href="{% url 'konekuser' %}">Sign in</a>
              
              {% endif %}
          
          
      </div>
    </div>
  </nav>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
   

  {% block content %}
    
  {% endblock content %}
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>
    
</body>

templates/pwoje/acceuil.html
{% extends "base.html" %}

{% block content %}
<hr>
<h3>Projet'w lan styl la </h3>

<a class="btn btn-primary" href="{% url 'aceuil'%}">Retour</a>
{% endblock content %}

templates/pwoje/delete.html
{% extends 'base.html' %}


{% block content %}
    <p>eskew ta renmen efase komand sa </p>
    <form action="" method="post">
        {% csrf_token %}
        <a class="btn btn-warning" href="{% url 'acceuil'%}">NON</a>
        <input class="btn btn-danger" type="submit" name="oui">
    </form>
{% endblock content %}
    

templates/pwoje/kreye.html
{% extends 'main.html' %}


{% block content %}
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css">
<body>
  <img src="https://i.ibb.co/XWdPc2X/wave-01.png" class="wave">
  <div class="container">
  <div style="overflow-x: hidden;" >
<div class="row g-lg-1">
   
    {% if user.is_authenticated %}
    
            <form class="row row-cols-md-4"  action="/pwoje/kreyee" method="post" enctype="multipart/form-data">
                <div class="col-md-4">
                    <div class="form-control-lg">
                            {% csrf_token %}
                            
                            {{form.as_p}}

                            <div class="m-5">
                                <button type="submit" class="btn btn-primary">KREYE</button>
                            </div>

                    </div>
                </div>    
                
                
            </form>
   {% endif %}
</div>
</div>
  </div>
</body>

<style>
  @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@500;600;700;800&display=swap');

  *{
	margin: 0;
	padding:0;
	box-sizing: border-box;
}
body{
font-family: 'Poppins', sans-serif;

}
.wave{
position: absolute;
bottom: 0;
left: 0;
height: 110%;
z-index: -1;
}
.container{
	width: 100vw;
	height: 70vh;
	display: block;
	grid-template-columns: repeat(2, 1fr);
	grid-gap: 7rem;
	padding: 0 2rem;
}
.btn:hover{
	background-position: right;
}

@media screen and (max-width: 1050px){
	.container{
		grid-gap: 5rem;
	}
}
@media screen and (max-width: 1000px){
	form{
		width: 290px;
	}
	.title{
		margin: 8px 0;
		font-size: 2.4rem;
	}
	.img img{
		width: 400px;
	}
}

@media screen and (max-width: 900px){
	body{
		background-color: #6b5cff;
	}
	.container{
		grid-template-columns: 1fr;
	}
	.img{
		display:none;
	}
	.wave{
		display:none;
	}
	.login-content{
		justify-content: center;
		color: #6b5cff;
	}
	.form-login{
		padding: 40px;
		background-color: #fff;
		width: 420px;
		border-radius: 8px;
		box-shadow: 3px 3px 15px rgba(88, 34, 160, 0.2);
	}
}
  </style>

{% endblock content %}

templates/pwoje/unprojet.html
{% extends 'main.html' %}
{% block content %}
<div style="overflow-x: hidden;" >
<div class="container-fluid">
	<div class="row">
	  <div class="col-xl-6 col-lg-6 col-md-6" style="border:1px solid #ddd">
		
		{% if un.foto %}
		<img src="{{un.foto.url}}" class="img-fluid">
		{% endif %}
			
		
	  </div>
	  <div class="col-xl-6 col-lg-6 col-md-6" style="border:1px solid #ddd">
		
		{% if un.titre %}
		<h3><strong>Titre:</strong>{{un.titre}}</h3>
		{% endif %}
		
		{% if un.description %}
		<p>Contenu: {{un.description}}</p>
		{% endif %}
		<p>Date: {{un.date}}</p>
	
		<p>{{un.kategori_set.all}}</p>
		
	  </div>
	</div>
</div>
</div>

{% endblock content %}

templates/user/acceuil.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>



 


{% for profil in Lis_itilizate %}

{% if profil.profile %}
<div class="card-group">
  <div class="card">
    <div class="custom-card card card mb-3 shadow" style="width: 18em;">
      
      {% if profil.profile.foto %}
      <img src="{{profil.profile.foto.url}}" alt="Avatar" class="card-img-top ">
      {% endif %}
      <div class="card-body">
  <h5 class="card-title">{{profil.profile.nom}} {{profil.siyati}}</h5>
  <p class="card-text"><a href="{% url 'onprofile' profil.id %}" class="btn btn-primary mb">Profile</a></p>
  </div>
</div>
</div>
</div>
 



    {% endif %}
  {% endfor %}


  <style>
    
	.mb.card-body{
    text-align: center;
}
.mb.btn{
    border-radius: 0;
    box-shadow: 0.5px 1px 2px hsla(0, 0%, 20%, 1);
}
.mb.btn:hover{
    transform: translateY(-2px);
    box-shadow: 2px 2px 5px hsla(0, 0%, 20%, 1);
}
.mb.card{
    border-radius: 0px / 0px;
    overflow: hidden;
    box-shadow: 0.5px 1px 2px hsla(0, 0%, 20%, 1);
}


  </style>
{% endblock content %}

templates/user/itilizate.html
{% extends 'main.html' %}


{% block content %}
<br>
<div style="overflow-x: hidden;" >
<div class="row">
	
	{% for moun in user %}
	  
	<div class="col-md">
		<div class="card card-body">
			<h5>Informations</h5>
			<hr>
			
			{% if moun.profile.foto %}	
    		<p>Pic: <img src="{{moun.profile.foto.url}}" alt=""></p>
			{% endif %}
            <p>Nom:{{moun.profile.siyati}} </p>
            <p>Prenom: {{moun.profile.nom}}</p>
            <p>Email: {{moun.profile.email}}</p>
			<p>tel: {{moun.profile.telefon}}</p>
			
		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Tous les projets</h5>
			<hr>
            <table class="table table-sm">
                
				
                        <tr>
						
							
						
                         <th></th>
						<th>Titre</th>
						 <th></th>
						</tr>
						{% for pro in moun.projet_set.all %}
						<tr>
						<th><a href="{% url 'youn' pro.slug %}" class="btn btn-primary btn-sm btn-block" style="text-decoration:none;">READ MORE</a></th>
						<th>{{pro.titre}}</th>
						<th>
						<th><a class="btn btn-sm btn-danger" href="{% url 'delete' pro.id %}">Supprimer</a></th>
						</tr>
						{% endfor %}
            </table>
			
			<h1 style="text-align: center;padding: 10px"><a class="btn btn-primary  btn-sm btn-block" href="{% url 'kreyee' %}">Add Another project</a></h1>
			
		</div>
	</div>
</div>
</div>
{% endfor %}
{% endblock content %}
    

templates/user/konekte.html
{% extends 'main.html' %}


{% block content %}




<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css">
</head>
<body>
  <img src="https://i.ibb.co/XWdPc2X/wave-01.png" class="wave">
  <div class="container">
    <div class="img">
      <img src="https://i.ibb.co/JvXP8rW/phone.png">
    </div>
    <div class="login-content">
      <form action="{% url 'konekuser' %}" class="form-login" method="post">
        {% csrf_token %}
        <img src="https://i.ibb.co/H4f3Hkv/profile.png">
        <h2 class="title">Welcome</h2>
        <div class="input-div one">
        <div class="i">
          <i class="fas fa-user"></i>
        </div>
        <div class="div">
          <h5>Username</h5>
          <input type="text" name="nom" id="nom" class="input">
        </div>
        </div>
        <div class="input-div pass">
        <div class="i">
          <i class="fas fa-lock"></i>
        </div>
        <div class="div">
          <h5>Password</h5>
          <input type="password" name="modpas" id="modpas" class="input">
        </div>
        </div>
        <input type="submit" class="btn" value="Login">
        
      </form>
    </div>
  </div>


  <!---JS CDN Link---->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <!--Custom File Link--->
  <script src="js.js"></script>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@500;600;700;800&display=swap');

*{
	margin: 0;
	padding:0;
	box-sizing: border-box;
}
body{
	font-family: 'Poppins', sans-serif;
	overflow: hidden;
}
.wave{
	position: fixed;
	bottom: 0;
	left: 0;
	height: 100%;
	z-index: -1;
}
.container{
	width: 100vw;
	height: 100vh;
	display: grid;
	grid-template-columns: repeat(2, 1fr);
	grid-gap: 7rem;
	padding: 0 2rem;
}
.img{
	display: flex;
	justify-content: flex-end;
	align-items: center;
}
.login-content{
	display: flex;
	justify-content: flex-start;
	align-items: center;
	text-align: center;
}
.img img{
	width: 500px;
}
form{
	width: 360px;
}
.login-content img{
	height: 100px;
}
.title{
	margin: 15px 0;
	color: #333;
	text-transform: uppercase;
	font-size: 2.9rem;
}
.login-content .input-div{
	position: relative;
	display: grid;
	grid-template-columns: 7% 93%;
	margin: 25px 0;
	padding: 5px 0;
	border-bottom: 2px solid #d9d9d9;
}
.login-content .input-div.one{
	margin-top: 0;
}
.i{
	color: #d9d9d9;
	display: flex;
	justify-content: center;
	align-items: center;
}
.i i{
	transition: .3s;
}
.input-div > div{
	position: relative;
	height: 45px;
}
.input-div > div > h5{
	position: absolute;
	left: 10px;
	top: 50%;
	transform: translateY(-50%);
	color: #999;
	font-size: 18px;
	transition: .3s;
}
.input-div:before, .input-div:after{
	content: '';
	position: absolute;
	bottom: -2px;
	width: 0%;
	height: 2px;
	background-color: #6b5cff;
	transition: .4s;
}
.input-div:before{
	right: 50%;
}
.input-div:after{
	left: 50%;
}
.input-div.focus:before, .input-div.focus:after{
	width: 50%;
}
.input-div.focus > div > h5{
	top: -5px;
	font-size: 15px;
}
.input-div.focus > .i > i{
	color: #6b5cff;
}
.input-div > div > input{
	position: absolute;
	left: 0;
	top: 0;
	width: 100%;
	height: 100%;
	border: none;
	outline: none;
	background: none;
	padding: 0.5rem 0.7rem;
	font-size: 1.2rem;
	color: #555;
}
.input-div.pass{
	margin-bottom: 4px;
}
a{
	display: block;
	text-align: center;
	text-decoration: none;
	color: #999;
	font-size: 0.9rem;
	transition: .3s;
}
a:hover{
	color: #6b5cff;
}
.btn{
	display: block;
	width: 100%;
	height: 50px;
	border-radius: 25px;
	outline: none;
	border: none;
	background-image: linear-gradient(to right, #6b5cff, #5d51c7, #6b5cff);
	background-size: 200%;
	font-size: 1.2rem;
	color: #fff;
	text-transform: uppercase;
	margin: 1rem 0;
	cursor: pointer;
	transition: .5s;
}
.btn:hover{
	background-position: right;
}

@media screen and (max-width: 1050px){
	.container{
		grid-gap: 5rem;
	}
}
@media screen and (max-width: 1000px){
	form{
		width: 290px;
	}
	.title{
		margin: 8px 0;
		font-size: 2.4rem;
	}
	.img img{
		width: 400px;
	}
}

@media screen and (max-width: 900px){
	body{
		background-color: #6b5cff;
	}
	.container{
		grid-template-columns: 1fr;
	}
	.img{
		display:none;
	}
	.wave{
		display:none;
	}
	.login-content{
		justify-content: center;
		color: #6b5cff;
	}
	.form-login{
		padding: 40px;
		background-color: #fff;
		width: 420px;
		border-radius: 8px;
		box-shadow: 3px 3px 15px rgba(88, 34, 160, 0.2);
	}
}
  </style>
<script type="text/javascript">
const inputs=document.querySelectorAll(".input");

function addCl() {
  let par=this.parentNode.parentNode;
  par.classList.add("focus");
}

function remC1() {
  let par=this.parentNode.parentNode;
  if(this.value=="")
  par.classList.remove("focus");
}

inputs.forEach(input=>{
  input.addEventListener("focus",addCl);
  input.addEventListener("blur",remC1);
})
</script>
   

     
{% endblock content %}
     